# Generated by Django 3.0.4 on 2020-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200526_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=0, upload_to='product', verbose_name='Imagen principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=0, upload_to='product', verbose_name='Imagen secundaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=0, upload_to='product', verbose_name='Imagen secundaria 2'),
            preserve_default=False,
        ),
    ]
