# Generated by Django 3.0.4 on 2020-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200523_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='level',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
